include: package:flutter_lints/flutter.yaml

linter:
  rules:
    library_prefixes: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    avoid_init_to_null: false
    prefer_const_constructors: false
    avoid_web_libraries_in_flutter: false
    unnecessary_const: false
    file_names: false
    use_function_type_syntax_for_parameters: false
    library_private_types_in_public_api: false
    prefer_const_literals_to_create_immutables: false
    camel_case_types: false
    prefer_function_declarations_over_variables: false
    prefer_const_constructors_in_immutables: false
    valid_regexps: false
    no_leading_underscores_for_local_identifiers: false
    prefer_interpolation_to_compose_strings: false
