name: botola_max
description: UEFA Champions League competitions, matches and much more

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  video_player: ^2.10.0
  provider: ^6.1.5
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  gap: ^3.0.1
  wakelock_plus: ^1.3.2
  visibility_detector: ^0.4.0+2
  timeago: ^3.7.1
  collection: ^1.19.0
  loading_animation_widget: ^1.3.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  animated_theme_switcher: ^2.0.10
  dio: ^5.8.0+1
  animated_flip_counter: ^0.3.4
  power_geojson: ^1.2.5+4
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  audioplayers: ^6.4.0

  flutter_svg:
    git:
      url: https://github.com/youmtinetflutterpacks/my_flutter_svg.git
      ref: v2.0.10+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.10+1

# dart pub global run rename setAppName --value ""
# dart pub global run rename setBundleId --value com.ymrabtiapps.botola_max

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/Qatar2022Arabic-Bold.ttf
        - asset: assets/fonts/Qatar2022Arabic-Heavy.ttf

  #
