name: uefa_champions_league
description: UEFA Champions League competitions, matches and much more

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  console_tools: ^1.0.0
  http: ^0.13.5
  just_audio: ^0.9.37
  get: ^4.6.5
  video_player: ^2.8.5
  provider: ^6.0.4
  flutter_svg: ^1.1.6
  path_provider: ^2.0.11
  path: ^1.8.2
  intl: ^0.17.0
  get_time_ago: ^1.1.8
  flutter_form_builder: ^8.0.0
  gap: ^3.0.1
  wakelock_plus: ^1.1.4
  visibility_detector: ^0.4.0+2
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.10+1

# dart run flutter_launcher_icons:main
flutter_icons:
  image_path: assets/logo-dark.png
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FF00004B"
  adaptive_icon_foreground: assets/logo-dark.png

  flutter_lints: ^1.0.0

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/logo-light.png
  image_dark: assets/logo-dark.png
  #   branding: assets/qatar-word.png
  color: "#00004b"
  color_dark: "#d8d8d8"
  #background_image: "assets/background.png"
  #background_image_dark: "assets/dark-background.png"

  android_12:
    image: assets/logo-light.png
    image_dark: assets/logo-dark.png
    # branding: assets/qatar-word.png
    color: "#00004b"
    color_dark: "#d8d8d8"

    # icon_background_color: "#111111"
    # icon_background_color_dark: "#eeeeee"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Qatar2022
      fonts:
        - asset: assets/Qatar2022/Qatar2022Arabic-Bold.ttf
        - asset: assets/Qatar2022/Qatar2022Arabic-Heavy.ttf

  #
