name: uefa_champions_league
description: UEFA Champions League competitions, matches and much more

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  console_tools: ^1.0.0
  just_audio: ^0.9.37
  get: ^4.6.5
  video_player: ^2.8.5
  provider: ^6.0.4
  flutter_svg: ^2.0.10+1
  path_provider: ^2.0.11
  path: ^1.8.2
  intl: ^0.17.0
  get_time_ago: ^1.1.8
  flutter_form_builder: ^8.0.0
  gap: ^3.0.1
  wakelock_plus: ^1.1.4
  visibility_detector: ^0.4.0+2
  timeago: ^3.3.0
  collection: ^1.17.2
  http: ^1.1.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
    path: ../../my-edited-packages/flutter_launcher_icons-master
  flutter_native_splash: ^2.2.10+1

# dart pub global run rename setAppName --value ""
# dart pub global run rename setBundleId --value com.ymrabtiapps.botola_max
# dart run flutter_native_splash:create
flutter_launcher_icons:
  image_path: "src/logo-botola-max.png"
  android: true
  ios: false
  remove_alpha_ios: true
  #   adaptive_icon_background: "#FF00004B"
  adaptive_icon_foreground: "src/logo-botola-max.png"

flutter_native_splash:
  image: src/logo-max-botola.png
  image_dark: src/logo-max-botola.png
  color: "#080808"
  color_dark: "#080808"

  android_12:
    image: src/logo-max-botola.png
    image_dark: src/logo-max-botola.png
    color: "#383838"
    color_dark: "#383838"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Qatar2022
      fonts:
        - asset: assets/Qatar2022/Qatar2022Arabic-Bold.ttf
        - asset: assets/Qatar2022/Qatar2022Arabic-Heavy.ttf

  #
