name: botola_max
description: UEFA Champions League competitions, matches and much more

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  console_tools: ^1.0.0
  just_audio: ^0.9.37
  get: ^4.6.5
  video_player: ^2.8.5
  provider: ^6.0.4
  path_provider: ^2.0.11
  path: ^1.9.0
  intl: ^0.17.0
  get_time_ago: ^1.1.8
  gap: ^3.0.1
  wakelock_plus: ^1.1.4
  visibility_detector: ^0.4.0+2
  timeago: ^3.3.0
  collection: ^1.17.2
  http: ^1.1.0
  loading_animation_widget: ^1.2.1
  uuid: ^4.2.2
  shared_preferences: ^2.2.3
  animated_theme_switcher: ^2.0.10
  dio: ^5.7.0
  timezone: ^0.9.4
  animated_flip_counter: ^0.3.3
  # flutter_svg: ^2.0.10+1
  flutter_svg:
    git:
      url: https://github.com/youmtinetflutterpacks/my_flutter_svg.git
      ref: v2.0.10+1
  power_geojson:
    git:
      url: https://github.com/youmtinetflutterpacks/power_geojson.git
      ref: v1.0.8+14(sdk3.1.0)
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.2.4
  audioplayers: ^5.2.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.10+1

# dart pub global run rename setAppName --value ""
# dart pub global run rename setBundleId --value com.ymrabtiapps.botola_max

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/Qatar2022Arabic-Bold.ttf
        - asset: assets/fonts/Qatar2022Arabic-Heavy.ttf

  #
