# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.builtInKotlin=false
android.useAndroidX=true
android.enableJetifier=true
# android.defaults.buildfeatures.buildconfig=true
# android.nonTransitiveRClass=false
# android.nonFinalResIds=false
