var testStandings = {
  "filters": {"season": "2024"},
  "area": {"id": 2077, "name": "Europe", "code": "EUR", "flag": "https://crests.football-data.org/EUR.svg"},
  "competition": {"id": 2001, "name": "UEFA Champions League", "code": "CL", "type": "CUP", "emblem": "https://crests.football-data.org/CL.png"},
  "season": {"id": 2350, "startDate": "2024-09-17", "endDate": "2025-05-31", "currentMatchday": 2, "winner": null},
  "standings": [
    {
      "stage": "GROUP_STAGE",
      "type": "TOTAL",
      "group": "League phase",
      "table": [
        {
          "position": 1,
          "team": {"id": 5, "name": "FC Bayern München", "shortName": "Bayern", "tla": "FCB", "crest": "https://crests.football-data.org/5.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 9,
          "goalsAgainst": 2,
          "goalDifference": 7
        },
        {
          "position": 2,
          "team": {"id": 732, "name": "Celtic FC", "shortName": "Celtic", "tla": "CEL", "crest": "https://crests.football-data.org/732.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 5,
          "goalsAgainst": 1,
          "goalDifference": 4
        },
        {
          "position": 3,
          "team": {"id": 3, "name": "Bayer 04 Leverkusen", "shortName": "Leverkusen", "tla": "B04", "crest": "https://crests.football-data.org/3.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 4,
          "goalsAgainst": 0,
          "goalDifference": 4
        },
        {
          "position": 4,
          "team": {"id": 58, "name": "Aston Villa FC", "shortName": "Aston Villa", "tla": "AVL", "crest": "https://crests.football-data.org/58.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 3,
          "goalsAgainst": 0,
          "goalDifference": 3
        },
        {
          "position": 4,
          "team": {"id": 4, "name": "Borussia Dortmund", "shortName": "Dortmund", "tla": "BVB", "crest": "https://crests.football-data.org/4.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 3,
          "goalsAgainst": 0,
          "goalDifference": 3
        },
        {
          "position": 6,
          "team": {"id": 907, "name": "AC Sparta Praha", "shortName": "Sparta Praha", "tla": "SPP", "crest": "https://crests.football-data.org/907.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 3,
          "goalsAgainst": 0,
          "goalDifference": 3
        },
        {
          "position": 7,
          "team": {"id": 64, "name": "Liverpool FC", "shortName": "Liverpool", "tla": "LIV", "crest": "https://crests.football-data.org/64.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 3,
          "goalsAgainst": 1,
          "goalDifference": 2
        },
        {
          "position": 8,
          "team": {"id": 109, "name": "Juventus FC", "shortName": "Juventus", "tla": "JUV", "crest": "https://crests.football-data.org/109.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 3,
          "goalsAgainst": 1,
          "goalDifference": 2
        },
        {
          "position": 8,
          "team": {"id": 86, "name": "Real Madrid CF", "shortName": "Real Madrid", "tla": "RMA", "crest": "https://crests.football-data.org/86.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 3,
          "goalsAgainst": 1,
          "goalDifference": 2
        },
        {
          "position": 10,
          "team": {"id": 498, "name": "Sporting Clube de Portugal", "shortName": "Sporting CP", "tla": "SPO", "crest": "https://crests.football-data.org/498.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 2,
          "goalsAgainst": 0,
          "goalDifference": 2
        },
        {
          "position": 11,
          "team": {"id": 1903, "name": "Sport Lisboa e Benfica", "shortName": "SL Benfica", "tla": "BEN", "crest": "https://crests.football-data.org/1903.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 2,
          "goalsAgainst": 1,
          "goalDifference": 1
        },
        {
          "position": 12,
          "team": {"id": 548, "name": "AS Monaco FC", "shortName": "Monaco", "tla": "ASM", "crest": "https://crests.football-data.org/548.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 2,
          "goalsAgainst": 1,
          "goalDifference": 1
        },
        {
          "position": 12,
          "team": {"id": 78, "name": "Club Atlético de Madrid", "shortName": "Atleti", "tla": "ATL", "crest": "https://crests.football-data.org/78.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 2,
          "goalsAgainst": 1,
          "goalDifference": 1
        },
        {
          "position": 12,
          "team": {"id": 512, "name": "Stade Brestois 29", "shortName": "Brest", "tla": "BRE", "crest": "https://crests.football-data.org/512.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 2,
          "goalsAgainst": 1,
          "goalDifference": 1
        },
        {
          "position": 15,
          "team": {"id": 524, "name": "Paris Saint-Germain FC", "shortName": "PSG", "tla": "PSG", "crest": "https://crests.football-data.org/524.png"},
          "playedGames": 1,
          "form": null,
          "won": 1,
          "draw": 0,
          "lost": 0,
          "points": 3,
          "goalsFor": 1,
          "goalsAgainst": 0,
          "goalDifference": 1
        },
        {
          "position": 16,
          "team": {"id": 57, "name": "Arsenal FC", "shortName": "Arsenal", "tla": "ARS", "crest": "https://crests.football-data.org/57.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 1,
          "lost": 0,
          "points": 1,
          "goalsFor": 0,
          "goalsAgainst": 0,
          "goalDifference": 0
        },
        {
          "position": 16,
          "team": {"id": 102, "name": "Atalanta BC", "shortName": "Atalanta", "tla": "ATA", "crest": "https://crests.football-data.org/102.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 1,
          "lost": 0,
          "points": 1,
          "goalsFor": 0,
          "goalsAgainst": 0,
          "goalDifference": 0
        },
        {
          "position": 16,
          "team": {"id": 103, "name": "Bologna FC 1909", "shortName": "Bologna", "tla": "BOL", "crest": "https://crests.football-data.org/103.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 1,
          "lost": 0,
          "points": 1,
          "goalsFor": 0,
          "goalsAgainst": 0,
          "goalDifference": 0
        },
        {
          "position": 16,
          "team": {"id": 108, "name": "FC Internazionale Milano", "shortName": "Inter", "tla": "INT", "crest": "https://crests.football-data.org/108.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 1,
          "lost": 0,
          "points": 1,
          "goalsFor": 0,
          "goalsAgainst": 0,
          "goalDifference": 0
        },
        {
          "position": 16,
          "team": {"id": 65, "name": "Manchester City FC", "shortName": "Man City", "tla": "MCI", "crest": "https://crests.football-data.org/65.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 1,
          "lost": 0,
          "points": 1,
          "goalsFor": 0,
          "goalsAgainst": 0,
          "goalDifference": 0
        },
        {
          "position": 16,
          "team": {"id": 1887, "name": "FK Shakhtar Donetsk", "shortName": "Shaktar", "tla": "SHD", "crest": "https://crests.football-data.org/1887.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 1,
          "lost": 0,
          "points": 1,
          "goalsFor": 0,
          "goalsAgainst": 0,
          "goalDifference": 0
        },
        {
          "position": 22,
          "team": {"id": 81, "name": "FC Barcelona", "shortName": "Barça", "tla": "FCB", "crest": "https://crests.football-data.org/81.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 2,
          "goalDifference": -1
        },
        {
          "position": 22,
          "team": {"id": 721, "name": "RB Leipzig", "shortName": "RB Leipzig", "tla": "RBL", "crest": "https://crests.football-data.org/721.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 2,
          "goalDifference": -1
        },
        {
          "position": 22,
          "team": {"id": 2021, "name": "SK Sturm Graz", "shortName": "Sturm Graz", "tla": "STU", "crest": "https://crests.football-data.org/2021.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 2,
          "goalDifference": -1
        },
        {
          "position": 25,
          "team": {"id": 7283, "name": "FK Crvena Zvezda", "shortName": "Crvena Zvedza", "tla": "CRV", "crest": "https://crests.football-data.org/7283.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 2,
          "goalDifference": -1
        },
        {
          "position": 26,
          "team": {"id": 298, "name": "Girona FC", "shortName": "Girona", "tla": "GIR", "crest": "https://crests.football-data.org/298.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 0,
          "goalsAgainst": 1,
          "goalDifference": -1
        },
        {
          "position": 27,
          "team": {"id": 674, "name": "PSV", "shortName": "PSV", "tla": "PSV", "crest": "https://crests.football-data.org/674.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 3,
          "goalDifference": -2
        },
        {
          "position": 27,
          "team": {"id": 10, "name": "VfB Stuttgart", "shortName": "Stuttgart", "tla": "VFB", "crest": "https://crests.football-data.org/10.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 3,
          "goalDifference": -2
        },
        {
          "position": 29,
          "team": {"id": 98, "name": "AC Milan", "shortName": "Milan", "tla": "MIL", "crest": "https://crests.football-data.org/98.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 3,
          "goalDifference": -2
        },
        {
          "position": 30,
          "team": {"id": 521, "name": "Lille OSC", "shortName": "Lille", "tla": "LIL", "crest": "https://crests.football-data.org/521.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 0,
          "goalsAgainst": 2,
          "goalDifference": -2
        },
        {
          "position": 31,
          "team": {"id": 1871, "name": "BSC Young Boys", "shortName": "Young Boys", "tla": "YOB", "crest": "https://crests.football-data.org/1871.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 0,
          "goalsAgainst": 3,
          "goalDifference": -3
        },
        {
          "position": 31,
          "team": {"id": 851, "name": "Club Brugge KV", "shortName": "Club Brugge", "tla": "CLU", "crest": "https://crests.football-data.org/851.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 0,
          "goalsAgainst": 3,
          "goalDifference": -3
        },
        {
          "position": 31,
          "team": {"id": 1877, "name": "FC Red Bull Salzburg", "shortName": "RB Salzburg", "tla": "RBS", "crest": "https://crests.football-data.org/1877.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 0,
          "goalsAgainst": 3,
          "goalDifference": -3
        },
        {
          "position": 34,
          "team": {"id": 7509, "name": "ŠK Slovan Bratislava", "shortName": "Sl. Bratislava", "tla": "SBA", "crest": "https://crests.football-data.org/7509.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 1,
          "goalsAgainst": 5,
          "goalDifference": -4
        },
        {
          "position": 35,
          "team": {"id": 675, "name": "Feyenoord Rotterdam", "shortName": "Feyenoord", "tla": "FEY", "crest": "https://crests.football-data.org/675.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 0,
          "goalsAgainst": 4,
          "goalDifference": -4
        },
        {
          "position": 36,
          "team": {"id": 755, "name": "GNK Dinamo Zagreb", "shortName": "Dinamo Zagreb", "tla": "DIN", "crest": "https://crests.football-data.org/755.png"},
          "playedGames": 1,
          "form": null,
          "won": 0,
          "draw": 0,
          "lost": 1,
          "points": 0,
          "goalsFor": 2,
          "goalsAgainst": 9,
          "goalDifference": -7
        }
      ]
    }
  ]
};
